export type {
  AnalysisResultV2,
  AntiPatternHit,
  AnalysisMeta,
  BeatMatch,
  Citation,
  Coverage,
  DeckRubricCategory,
  DeliveryMetrics,
  FeedbackOutput,
  FillerWord,
  Fix,
  FixImpact,
  OneMinuteQAPack,
  PatternSnippet,
  PitchStage,
  RepeatedPhrase,
  RubricCategory,
  RubricScore,
  ScoreCategory,
  ScoringContext,
  SentimentProfile,
  StageExpectation,
} from '@/types/analysis-v2';

export type AnalysisResult = import('@/types/analysis-v2').FeedbackOutput;
