export type {
  AnalysisResultV2,
  AntiPatternHit,
  AnalysisMeta,
  BeatMatch,
  Citation,
  Coverage,
  DeckRubricCategory,
  DeckSlideLink,
  DeliveryEvent,
  DeliveryEventType,
  DeliveryMetrics,
  FeedbackOutput,
  FillerWord,
  Fix,
  FixImpact,
  HistoricalLink,
  HistoricalScoreDelta,
  OneMinuteQAPack,
  PatternSnippet,
  PitchStage,
  RepeatedPhrase,
  RewriteDiff,
  RewriteDiffGrammarTag,
  RewriteDiffHunk,
  RewriteDiffToken,
  RewriteDiffTokenKind,
  RubricCategory,
  RubricScore,
  ScoreCategory,
  SectionBeat,
  SectionFeedback,
  ScoringContext,
  SentimentProfile,
  StageExpectation,
  TranscriptSegment,
  TranscriptWord,
  VocabularyMetrics,
  VocabularyTermStat,
} from '@/types/analysis-v2';

export type AnalysisResult = import('@/types/analysis-v2').FeedbackOutput;
