import { promises as fs } from 'fs';
import path from 'path';
import { PROJECT_TYPE_DEFINITIONS } from '@/config/projectTypes';

interface RunnerManifestRow {
  projectType: string;
  label: string;
  workflowMode: string;
  outDir: string;
  ps1Path: string;
  cmdPath: string;
  shPath: string;
  command: string;
}

function toPosix(relativePath: string): string {
  return relativePath.replace(/\\/gu, '/');
}

function sanitize(value: string): string {
  return value.replace(/[^a-z0-9_-]+/giu, '_').toLowerCase();
}

function buildPs1Script(projectType: string, workflowMode: string, outDir: string): string {
  return [
    'param(',
    '  [string]$Cases = "tests/fixtures/rubric-sandbox/cases.json",',
    '  [ValidateSet("case-or-default","case-only")]',
    '  [string]$CustomPolicy = "case-or-default",',
    `  [string]$OutDir = "${outDir}"`,
    ')',
    '',
    '$ErrorActionPreference = "Stop"',
    '$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\\..\\..")',
    'Set-Location $RepoRoot',
    '',
    `yarn rubric:matrix:anthropic --mode ${workflowMode} --cases "$Cases" --custom-policy "$CustomPolicy" --out-dir "$OutDir"`,
    '',
  ].join('\n');
}

function buildCmdScript(projectType: string, workflowMode: string, outDir: string): string {
  return [
    '@echo off',
    'setlocal',
    'set REPO_ROOT=%~dp0\\..\\..\\..',
    'pushd "%REPO_ROOT%"',
    `yarn rubric:matrix:anthropic --mode ${workflowMode} --out-dir "${outDir}" %*`,
    'popd',
    '',
  ].join('\n');
}

function buildShScript(projectType: string, workflowMode: string, outDir: string): string {
  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    'REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"',
    'cd "${REPO_ROOT}"',
    `yarn rubric:matrix:anthropic --mode ${workflowMode} --out-dir "${outDir}" "$@"`,
    '',
  ].join('\n');
}

function buildRegistryMarkdown(rows: RunnerManifestRow[]): string {
  const lines: string[] = [];
  lines.push('# Rubric Matrix Runner Registry');
  lines.push('');
  lines.push('Auto-generated by `yarn sync:rubric-matrix-runners`.');
  lines.push('');
  lines.push('Use these scripts to run Anthropic-only rubric influence matrix tests per project type.');
  lines.push('');
  lines.push('| Project Type | Workflow Mode | Terminal Command | Generated Scripts |');
  lines.push('|---|---|---|---|');
  for (const row of rows) {
    lines.push(
      `| \`${row.projectType}\` (${row.label}) | \`${row.workflowMode}\` | \`${row.command}\` | [ps1](${row.ps1Path}), [cmd](${row.cmdPath}), [sh](${row.shPath}) |`,
    );
  }
  lines.push('');
  lines.push('## Notes');
  lines.push('');
  lines.push('- Add new project types in `config/projectTypes.ts`.');
  lines.push('- Re-run `yarn sync:rubric-matrix-runners` (also runs automatically in `predev` and `prebuild`).');
  lines.push('- Each runner writes results to its own out-dir under `.cache/rubric-sandbox/`.');
  lines.push('');
  return lines.join('\n');
}

async function removeExistingGeneratedFiles(dir: string): Promise<void> {
  const exists = await fs
    .access(dir)
    .then(() => true)
    .catch(() => false);
  if (!exists) return;
  const entries = await fs.readdir(dir, { withFileTypes: true });
  await Promise.all(
    entries
      .filter((entry) => entry.isFile())
      .map((entry) => fs.unlink(path.join(dir, entry.name))),
  );
}

async function main(): Promise<void> {
  const repoRoot = process.cwd();
  const generatedDir = path.join(repoRoot, 'scripts', 'generated', 'rubric-matrix');
  const registryPath = path.join(repoRoot, 'docs', 'rubric-matrix-runners.md');
  const registryDir = path.dirname(registryPath);

  await fs.mkdir(generatedDir, { recursive: true });
  await removeExistingGeneratedFiles(generatedDir);

  const rows: RunnerManifestRow[] = [];

  for (const item of PROJECT_TYPE_DEFINITIONS) {
    const typeId = sanitize(item.id);
    const workflowMode = item.workflowMode;
    const outDir = `.cache/rubric-sandbox/matrix-anthropic-${typeId}`;
    const baseName = `run-${typeId}`;

    const ps1File = path.join(generatedDir, `${baseName}.ps1`);
    const cmdFile = path.join(generatedDir, `${baseName}.cmd`);
    const shFile = path.join(generatedDir, `${baseName}.sh`);

    await fs.writeFile(ps1File, buildPs1Script(typeId, workflowMode, outDir), 'utf8');
    await fs.writeFile(cmdFile, buildCmdScript(typeId, workflowMode, outDir), 'utf8');
    await fs.writeFile(shFile, buildShScript(typeId, workflowMode, outDir), 'utf8');

    // Make shell scripts executable on POSIX systems.
    await fs.chmod(shFile, 0o755).catch(() => undefined);

    rows.push({
      projectType: item.id,
      label: item.label,
      workflowMode,
      outDir,
      ps1Path: toPosix(path.relative(registryDir, ps1File)),
      cmdPath: toPosix(path.relative(registryDir, cmdFile)),
      shPath: toPosix(path.relative(registryDir, shFile)),
      command: `yarn rubric:matrix:anthropic --mode ${workflowMode} --out-dir "${outDir}"`,
    });
  }

  const markdown = buildRegistryMarkdown(rows);
  await fs.writeFile(registryPath, markdown, 'utf8');

  console.log(`[sync-runners] generated ${rows.length} project-type runner sets in ${generatedDir}`);
  console.log(`[sync-runners] registry updated: ${registryPath}`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`[sync-runners] fatal: ${message}`);
  process.exitCode = 1;
});
